apiVersion: apps/v1
kind: Deployment
metadata:
  name: mininet-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mininet
  template:
    metadata:
      labels:
        app: mininet
    spec:
      containers:
      - name: mininet
        image: iwaseyusuke/mininet
        ports:
        - containerPort: 90
