#!/usr/bin/python

from mininet.net import Mininet
from mininet.node import Controller, RemoteController, OVSKernelSwitch, UserSwitch, Host, OVSBridge, OVSSwitch
from mininet.cli import CLI
from mininet.log import setLogLevel
from mininet.link import Link, TCLink


def myNetwork():

    CONTROLLER_IP1='172.17.0.4'
    CONTROLLER_IP2='172.17.0.3'

    net = Mininet( topo=None, controller=RemoteController, switch=OVSSwitch)

    print '* Add hosts\n'
    h1 = net.addHost('h1', mac='00:00:00:00:00:01', ip='10.0.0.1')
    h2 = net.addHost('h2', mac='00:00:00:00:00:02',  ip='10.0.0.2')
    h3 = net.addHost('h3', mac='00:00:00:00:00:03', ip='10.0.0.3')
    h4 = net.addHost('h4', mac='00:00:00:00:00:04', ip='10.0.0.4')
    h5 = net.addHost('h5', mac='00:00:00:00:00:05',  ip='10.0.0.5')
    h6 = net.addHost('h6', mac='00:00:00:00:00:06',  ip='10.0.0.6')
    h7 = net.addHost('h7', mac='00:00:00:00:00:07',  ip='10.0.0.7')
    h8 = net.addHost('h8', mac='00:00:00:00:00:08', ip='10.0.0.8')
    h9 = net.addHost('h9', mac='00:00:00:00:00:09',  ip='10.0.0.9')
    h10 = net.addHost('h10', mac='00:00:00:00:00:10', ip='10.0.0.10')
    h11 = net.addHost('h11', mac='00:00:00:00:00:11', ip='10.0.0.11')
    h12 = net.addHost('h12', mac='00:00:00:00:00:12', ip='10.0.0.12')
    h13 = net.addHost('h13', mac='00:00:00:00:00:13',  ip='10.0.0.13')
    h14 = net.addHost('h14', mac='00:00:00:00:00:14',  ip='10.0.0.14')
    h15 = net.addHost('h15', mac='00:00:00:00:00:15',  ip='10.0.0.15')
    h16 = net.addHost('h16', mac='00:00:00:00:00:16',  ip='10.0.0.16')
    h17 = net.addHost('h17', mac='00:00:00:00:00:17', ip='10.0.0.17')
    h18 = net.addHost('h18', mac='00:00:00:00:00:18',  ip='10.0.0.18')
    h19 = net.addHost('h19', mac='00:00:00:00:00:19',  ip='10.0.0.19')
    h20 = net.addHost('h20', mac='00:00:00:00:00:20',  ip='10.0.0.20')
    h21 = net.addHost('h21', mac='00:00:00:00:00:21',  ip='10.0.0.21')
    h22 = net.addHost('h22', mac='00:00:00:00:00:22',  ip='10.0.0.22')
    h23 = net.addHost('h23', mac='00:00:00:00:00:23', ip='10.0.0.23')
    h24 = net.addHost('h24', mac='00:00:00:00:00:24',  ip='10.0.0.24')



    print '* Add switches\n'
    s1 = net.addSwitch('s1', cls=OVSSwitch, protocols='OpenFlow13')
    s2 = net.addSwitch('s2', cls=OVSSwitch, protocols='OpenFlow13')
    s3 = net.addSwitch('s3', cls=OVSSwitch, protocols='OpenFlow13')
    s4 = net.addSwitch('s4', cls=OVSSwitch, protocols='OpenFlow13')
    s5 = net.addSwitch('s5', cls=OVSSwitch, protocols='OpenFlow13')
    s6 = net.addSwitch('s6', cls=OVSSwitch, protocols='OpenFlow13')
    s7 = net.addSwitch('s7', cls=OVSSwitch, protocols='OpenFlow13')
    s8 = net.addSwitch('s8', cls=OVSSwitch, protocols='OpenFlow13')
    s9 = net.addSwitch('s9', cls=OVSSwitch, protocols='OpenFlow13')
    s10 = net.addSwitch('s10', cls=OVSSwitch, protocols='OpenFlow13')
    s11 = net.addSwitch('s11', cls=OVSSwitch, protocols='OpenFlow13')
    s12 = net.addSwitch('s12', cls=OVSSwitch, protocols='OpenFlow13')
    s13 = net.addSwitch('s13', cls=OVSSwitch, protocols='OpenFlow13')
    s14 = net.addSwitch('s14', cls=OVSSwitch, protocols='OpenFlow13')
    s15 = net.addSwitch('s15', cls=OVSSwitch, protocols='OpenFlow13')
    s16 = net.addSwitch('s16', cls=OVSSwitch, protocols='OpenFlow13')
    s17 = net.addSwitch('s17', cls=OVSSwitch, protocols='OpenFlow13')
    s18 = net.addSwitch('s18', cls=OVSSwitch, protocols='OpenFlow13')


    print '* Adding controller\n'
    c0 = net.addController( 'c0', controller=RemoteController, ip=CONTROLLER_IP1)
    c1 = net.addController( 'c1', controller=RemoteController, ip=CONTROLLER_IP2)
    print '* Add links\n'
    net.addLink(s1, s5)
    net.addLink(s1, s6)
    net.addLink(s1, s7)
    net.addLink(s2, s8)
    net.addLink(s2, s9)
    net.addLink(s2, s10)
    net.addLink(s3, s11)
    net.addLink(s3, s12)
    net.addLink(s3, s13)
    net.addLink(s4, s14)
    net.addLink(s4, s15)
    net.addLink(s4, s16)
    net.addLink(s5, h1)
    net.addLink(s5, h2)
    net.addLink(s17, s1)
    net.addLink(s17, s2)
    net.addLink(s18, s3)
    net.addLink(s18, s4)
    net.addLink(s6, h3)
    net.addLink(s6, h4)
    net.addLink(s7, h5)
    net.addLink(s7, h6)
    net.addLink(s8, h7)
    net.addLink(s8, h8)
    net.addLink(s9, h9)
    net.addLink(s9, h10)
    net.addLink(s10, h11)
    net.addLink(s10, h12)
    net.addLink(s11, h13)
    net.addLink(s11, h14)
    net.addLink(s12, h15)
    net.addLink(s12, h16)
    net.addLink(s13, h17)
    net.addLink(s13, h18)
    net.addLink(s14, h19)
    net.addLink(s14, h20)
    net.addLink(s15, h21)
    net.addLink(s15, h22)
    net.addLink(s16, h23)
    net.addLink(s16, h24)


    print '* Starting network\n'
    net.build()
    print '* Starting controllers\n'
    c0.start()
    c1.start()
    print '* Starting switches\n'
    net.get('s1').start([c0])
    net.get('s2').start([c0])
    net.get('s3').start([c1])
    net.get('s4').start([c1])
    net.get('s5').start([c0])
    net.get('s6').start([c0])
    net.get('s7').start([c0])
    net.get('s8').start([c0])
    net.get('s9').start([c0])
    net.get('s10').start([c0])
    net.get('s11').start([c1])
    net.get('s12').start([c1])
    net.get('s13').start([c1])
    net.get('s14').start([c1])
    net.get('s15').start([c1])
    net.get('s16').start([c1])
    net.get('s17').start([c0])
    net.get('s18').start([c1])

    CLI(net)
    net.stop()

if _name_ == '_main_':
    setLogLevel( 'info' )
    myNetwork()
